language: minimal
branchs:
  only:
    - master

after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- find . -type f -exec curl --ftp-create-dirs --key /tmp/sftp_rsa -T {} sftp://${SFTP_USER}:${SFTP_PASSWORD}@tranqyll.fr/nihongo/{} \;
