language: minimal
branchs:
  only:
    - master

before_install:
  - sudo apt-get -y install sshpass

after_success:
  - echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
  - sshpass -p ${SFTP_PASSWORD} scp -i /tmp/sftp_rsa -r ./* ${SFTP_USER}@tranqyll.fr:nihongo/
  